name: Build

on:
  push:
    branches:
      - 'release/*'
      - 'pipeline*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install Poetry on Unix
      if: runner.os != 'Windows'
      run: curl -sSL https://install.python-poetry.org | python3 -
      shell: bash

    - name: Install Poetry on Windows
      if: runner.os == 'Windows'
      run: (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | py -
      shell: pwsh

    - name: Install dependencies
      run: poetry install

    - name: Build app
      run: poetry run PyInstaller app.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-${{ matrix.os }}
        path: dist/app