name: Build

on:
  push:
    branches:
      - 'release/*'
      - 'pipeline-build'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Add Poetry to PATH on Windows
      if: runner.os == 'Windows'
      run: |
        $poetryPath = "$env:POETRY_HOME\bin"
        echo "Adding Poetry to PATH: $poetryPath"
        echo "$poetryPath" | Out-File -Append -FilePath $env:GITHUB_PATH -Encoding utf8

    - name: Directly Invoke Poetry Using Full Path
      if: runner.os == 'Windows'
      run: |
        $poetryFullPath = "$env:POETRY_HOME\bin\poetry"
        "& $poetryFullPath --version"

    - name: Install dependencies
      if: runner.os == 'Windows'
      run: |
        $poetryFullPath = "$env:POETRY_HOME\bin\poetry"
        "& $poetryFullPath install"
      else:
        run: poetry install

    - name: Build app
      if: runner.os == 'Windows'
      run: |
        $poetryFullPath = "$env:POETRY_HOME\bin\poetry"
        "& $poetryFullPath run PyInstaller app.spec"
      else:
        run: poetry run PyInstaller app.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-${{ matrix.os }}
        path: dist/app