name: Build

on:
  push:
    branches:
      - 'release/*'
      - 'pipeline-build'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Set up Poetry Path
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "POETRY_PATH=$env:USERPROFILE\.poetry\bin\poetry" >> $GITHUB_ENV
        else
          echo "POETRY_PATH=$HOME/.poetry/bin/poetry" >> $GITHUB_ENV
        fi

    - name: Install dependencies
      run: |
        ${{ env.POETRY_PATH }} install

    - name: Build app
      run: |
        ${{ env.POETRY_PATH }} run PyInstaller app.spec

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: app-${{ matrix.os }}
        path: dist/app